### ISSUE TITLE
Only works when the language chosen is Chinese

### ISSUE THREAD

**Issue by alwaysmiddle** [johnmave126/genshin-gacha-exporter#2]
Error message when using none Chinese Language as game display options.

Tested following: 
- [x] Simplified Chinese (Works)

- [x] Traditional Chinese (Works)

- [ ] Korean (Do not work)

- [ ] Japanese (Do not work)

- [ ] English (Do not work)

Error Message: 
Got same error in 32bit and 64bit version, all error messages were the same for all languages tested.

![[Bug Error Message][bug-error-message]](https://i.imgur.com/HRr5J1N.png)

**Comment by johnmave126** [comment]
I figured out that for languages that doesn't have micro-languages (for Chinese there are zh-cn and zh-tw), only ISO 639-1 macro code is present in the query. I need to find some way to convert ISO 639-1 to a default ISO 3166‑1 country code to fetch json.

**Comment by johnmave126** [comment]
Fixed in 01a053e6b1007a48e83f666540b88b3a54e48c9f
May be released a few days later with v0.2.4 after I figure out how to print non-ascii characters in win 7/8/8.1
