### ISSUE TITLE
1.3版本 獲取連結出現錯誤訊息

### ISSUE THREAD

**Issue by NeiL978** [johnmave126/genshin-gacha-exporter#4]
[1/2]√ 已加载卡池列表
[2/2]√ 已加载图鉴
√ 请选择需要查询的卡池 · 角色活動祈願
错误: 获取抽卡记录失败

Caused by:
    0: error decoding response body: cannot parse integer from empty string at line 1 column 129
    1: cannot parse integer from empty string at line 1 column 129
按回车键退出:

**Comment by johnmave126** [comment]
Fixed in https://github.com/johnmave126/genshin-gacha-exporter/releases/tag/v0.2.5
